name: Build and publish LaTeX
on: push
jobs:
  build-and-publish:
    strategy:
      matrix:
        files:
          [
            {
              file: "bachelor-1/semester-1/algebra-and-number-theory/main.pdf",
              name: "algebra-and-number-theory-1.pdf",
            },
            {
              file: "bachelor-1/semester-1/geometry-and-topology/main.pdf",
              name: "geometry-and-topology-1.pdf",
            },
            {
              file: "bachelor-1/semester-2/geometry-and-topology/main.pdf",
              name: "geometry-and-topology-2.pdf",
            },
            {
              file: "bachelor-2/semester-3/algebra-and-number-theory/main.pdf",
              name: "algebra-and-number-theory-3.pdf",
            },
            {
              file: "bachelor-2/semester-3/geometry-and-topology/main.pdf",
              name: "geometry-and-topology-3.pdf",
            },
            {
              file: "bachelor-2/semester-3/mathan/main.pdf",
              name: "pdfs/analysis-3.pdf",
            },
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.files.name }}
          work_in_root_file_dir: true
          latexmk_use_lualatex: true

      - name: Rename PDF
        run: mv ${{ matrix.files.file }} ${{ matrix.files.name }}

      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.files.name }}
          path: ${{ matrix.files.name }}
