name: Build and publish LaTeX
on: push
jobs:
  build-and-publish:
    strategy:
      matrix:
        files:
          [
            {
              tex_file: "bachelor-1/semester-1/algebra-and-number-theory/main.tex",
              pdf_file: "bachelor-1/semester-1/algebra-and-number-theory/main.pdf",
              upload_name: "algebra-and-number-theory-1.pdf",
            },
            {
              tex_file: "bachelor-1/semester-1/geometry-and-topology/main.tex",
              pdf_file: "bachelor-1/semester-1/geometry-and-topology/main.pdf",
              upload_name: "geometry-and-topology-1.pdf",
            },
            {
              tex_file: "bachelor-1/semester-2/geometry-and-topology/main.tex",
              pdf_file: "bachelor-1/semester-2/geometry-and-topology/main.pdf",
              upload_name: "geometry-and-topology-2.pdf",
            },
            {
              tex_file: "bachelor-2/semester-3/algebra-and-number-theory/main.tex",
              pdf_file: "bachelor-2/semester-3/algebra-and-number-theory/main.pdf",
              upload_name: "algebra-and-number-theory-3.pdf",
            },
            {
              tex_file: "bachelor-2/semester-3/geometry-and-topology/main.tex",
              pdf_file: "bachelor-2/semester-3/geometry-and-topology/main.pdf",
              upload_name: "geometry-and-topology-3.pdf",
            },
            {
              tex_file: "bachelor-2/semester-3/mathan/main.tex",
              pdf_file: "bachelor-2/semester-3/mathan/main.pdf",
              upload_name: "analysis-3.pdf",
            },
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.files.tex_file }}
          work_in_root_file_dir: true
          latexmk_use_lualatex: true

      - name: Rename PDF
        run: mv ${{ matrix.files.pdf_file }} ${{ matrix.files.upload_name }}

      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.files.upload_name }}
          path: ${{ matrix.files.upload_name }}
